import "~/styles/globals.css";

import About from "./page";
import Navbar from "../dashboard/navbar/page";
import { ScrollArea } from "@radix-ui/react-scroll-area";
import { Sidebar } from "lucide-react";
export const metadata = {
  title: "About MSNS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo/logo-white.png" }],
};

export default function AboutLayout({
}: {
  children: React.ReactNode;
}) {
  return (
    <body>
            <Navbar/>
            <Sidebar />
      <ScrollArea className="rounded-lg bg-emerald-200 shadow-md p-4 mt-4 ml-10">
      <About />
    </ScrollArea>
    </body>
  );
}
